export const CommonImageUpload = {
  COMMON_IMAGE_UPLOAD: "COMMON_IMAGE_UPLOAD",
  COMMON_IMAGE_UPLOAD_SUCCESS: "COMMON_IMAGE_UPLOAD_SUCCESS",
  COMMON_IMAGE_UPLOAD_ERROR_SHOW: "COMMON_IMAGE_UPLOAD_ERROR_SHOW",
  COMMON_IMAGE_UPLOAD_ERROR_HIDE: "COMMON_IMAGE_UPLOAD_ERROR_HIDE",
  COMMON_IMAGE_UPLOAD_STATE_CLEAR: "COMMON_IMAGE_UPLOAD_STATE_CLEAR",
};

export const CommonFileUpload = {
  COMMON_FILE_UPLOAD: "COMMON_FILE_UPLOAD",
  COMMON_FILE_UPLOAD_SUCCESS: "COMMON_FILE_UPLOAD_SUCCESS",
  COMMON_FILE_UPLOAD_ERROR_SHOW: "COMMON_FILE_UPLOAD_ERROR_SHOW",
  COMMON_FILE_UPLOAD_ERROR_HIDE: "COMMON_FILE_UPLOAD_ERROR_HIDE",
  COMMON_FILE_UPLOAD_STATE_CLEAR: "COMMON_FILE_UPLOAD_STATE_CLEAR",
};

export const CommonCollection = {
  GET_COMMON_COLLECTION_LIST: "GET_COMMON_COLLECTION_LIST",
  GET_COMMON_COLLECTION_LIST_SUCCESS: "GET_COMMON_COLLECTION_LIST_SUCCESS",
  GET_COMMON_COLLECTION_LIST_ERROR: "GET_COMMON_COLLECTION_LIST_ERROR",
};
export const CommonCardBinAllType = {
  GET_COMMON_CARD_BIN_ALL: "GET_COMMON_CARD_BIN_ALL",
  GET_COMMON_CARD_BIN_ALL_SUCCESS: "GET_COMMON_CARD_BIN_ALL_SUCCESS",
  GET_COMMON_CARD_BIN_ALL_ERROR: "GET_COMMON_CARD_BIN_ALL_ERROR",
};

export const CATEGORY_LIST_LOAD_SUCCESS = "CATEGORY_LIST_LOAD_SUCCESS";
export const GET_CATEGORY_LIST_COMMON = "GET_CATEGORY_LIST_COMMON";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";

export const BRAND_LIST_LOAD_SUCCESS = "BRAND_LIST_LOAD_SUCCESS";
export const GET_BRAND_LIST_COMMON = "GET_BRAND_LIST_COMMON";
export const BRAND_LIST_ERROR = "BRAND_LIST_ERROR";

export const MERCHANT_COMMON_LIST_LOAD_SUCCESS =
  "MERCHANT_COMMON_LIST_LOAD_SUCCESS";
export const GET_MERCHANT_COMMON_LIST = "GET_MERCHANT_COMMON_LIST";
export const MERCHANT_COMMON_LIST_ERROR = "MERCHANT_COMMON_LIST_ERROR";

export const HIGHLIGHT_LIST_LOAD_SUCCESS = "HIGHLIGHT_LIST_LOAD_SUCCESS";
export const GET_HIGHLIGHT_LIST_SPEC = "GET_HIGHLIGHT_LIST_SPEC";
export const HIGHLIGHT_LIST_ERROR = "HIGHLIGHT_LIST_ERROR";

export const OPTION_LIST_LOAD_SUCCESS = "OPTION_LIST_LOAD_SUCCESS";
export const GET_OPTION_LIST = "GET_OPTION_LIST";
export const OPTION_LIST_ERROR = "OPTION_LIST_ERROR";

export const WARRANTY_TYPE_LIST_LOAD_SUCCESS =
  "WARRANTY_TYPE_LIST_LOAD_SUCCESS";
export const GET_WARRANTY_TYPE_LIST = "GET_WARRANTY_TYPE_LIST";
export const WARRANTY_TYPE_LIST_ERROR = "WARRANTY_TYPE_LIST_ERROR";

export const WARRANTY_PERIOD_LIST_LOAD_SUCCESS =
  "WARRANTY_PERIOD_LIST_LOAD_SUCCESS";
export const GET_WARRANTY_PERIOD_LIST = "GET_WARRANTY_PERIOD_LIST";
export const WARRANTY_PERIOD_LIST_ERROR = "WARRANTY_PERIOD_LIST_ERROR";

export const GET_COMMON_HIGHLIGHT_ALL = "GET_COMMON_HIGHLIGHT_ALL";
export const GET_COMMON_HIGHLIGHT_ALL_SUCCESS =
  "GET_COMMON_HIGHLIGHT_ALL_SUCCESS";
export const GET_COMMON_HIGHLIGHT_ALL_ERROR = "GET_COMMON_HIGHLIGHT_ALL_ERROR";

export const GET_COMMON_PRODUCT_LIST_LOAD_SUCCESS =
  "GET_COMMON_PRODUCT_LIST_LOAD_SUCCESS";
export const GET_COMMON_PRODUCT_LIST = "GET_COMMON_PRODUCT_LIST";
export const GET_COMMON_PRODUCT_LIST_ERROR = "GET_COMMON_PRODUCT_LIST_ERROR";

export const CUSTOMER_SEGMENT_LIST_COMMON_LOAD_SUCCESS =
  "CUSTOMER_SEGMENT_LIST_COMMON_LOAD_SUCCESS";
export const GET_CUSTOMER_SEGMENT_LIST_COMMON =
  "GET_CUSTOMER_SEGMENT_LIST_COMMON";
export const CUSTOMER_SEGMENT_LIST_COMMON_ERROR =
  'CUSTOMER_SEGMENT_LIST_COMMON_ERROR';

export const LOG_HISTORY_LOAD_SUCCESS = 'LOG_HISTORY_LOAD_SUCCESS';
export const GET_LOG_HISTORY_COMMON = 'GET_LOG_HISTORY_COMMON';
export const LOG_HISTORY_ERROR_SHOW = 'LOG_HISTORY_ERROR_SHOW';
export const LOG_HISTORY_ERROR_HIDE = 'LOG_HISTORY_ERROR_HIDE';
export const GET_COMMON_CARD_TYPE_LOAD_SUCCESS ='GET_COMMON_CARD_TYPE_LOAD_SUCCESS';
export const GET_COMMON_CARD_TYPE = 'GET_COMMON_CARD_TYPE';
export const GET_COMMON_CARD_TYPE_ERROR = 'GET_COMMON_CARD_TYPE_ERROR';

export const BANK_LIST_LOAD_SUCCESS = 'BANK_LIST_LOAD_SUCCESS';
export const GET_BANK_LIST = 'GET_BANK_LIST';
export const BANK_LIST_ERROR = 'BANK_LIST_ERROR';

export const COUNTRY_LIST_LOAD_SUCCESS = 'COUNTRY_LIST_LOAD_SUCCESS';
export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const COUNTRY_LIST_ERROR = 'COUNTRY_LIST_ERROR';

export const CommonCategoryTree = {
  GET_COMMON_CATEGORY_TREE: "GET_COMMON_CATEGORY_TREE",
  GET_COMMON_CATEGORY_TREE_SUCCESS: "GET_COMMON_CATEGORY_TREE_SUCCESS",
  GET_COMMON_CATEGORY_TREE_ERROR: "GET_COMMON_CATEGORY_TREE_ERROR",
};

export const CommonCatlogRootTree = {
  GET_ROOT_CATLOG_TREE: "GET_ROOT_CATLOG_TREE",
  GET_ROOT_CATLOG_TREE_SUCCESS: "GET_ROOT_CATLOG_TREE_SUCCESS",
  GET_ROOT_CATLOG_TREE_ERROR: "GET_ROOT_CATLOG_TREE_ERROR",
};

export const CommonElasticProductSearch = {
  PRODUCT_SEARCH_ELASTIC: "PRODUCT_SEARCH_ELASTIC",
  PRODUCT_SEARCH_ELASTIC_SUCCESS: "PRODUCT_SEARCH_ELASTIC_SUCCESS",
  PRODUCT_SEARCH_ELASTIC_ERROR_SHOW: "PRODUCT_SEARCH_ELASTIC_ERROR_SHOW",
  PRODUCT_SEARCH_ELASTIC_ERROR_HIDE: "PRODUCT_SEARCH_ELASTIC_ERROR_HIDE",
};

export const CommonElasticProductSearchForBackoffice = {
  PRODUCT_SEARCH_ELASTIC_BACKOFFICE: "PRODUCT_SEARCH_ELASTIC_BACKOFFICE",
  PRODUCT_SEARCH_ELASTIC_SUCCESS_BACKOFFICE: "PRODUCT_SEARCH_ELASTIC_SUCCESS_BACKOFFICE",
  PRODUCT_SEARCH_ELASTIC_ERROR_SHOW_BACKOFFICE: "PRODUCT_SEARCH_ELASTIC_ERROR_SHOW_BACKOFFICE",
  PRODUCT_SEARCH_ELASTIC_ERROR_HIDE_BACKOFFICE: "PRODUCT_SEARCH_ELASTIC_ERROR_HIDE_BACKOFFICE",
};

export const DistrictAllType = {
  GET_DISTRICT_ALL: "GET_DISTRICT_ALL",
  GET_DISTRICT_ALL_SUCCESS: "GET_DISTRICT_ALL_SUCCESS",
  GET_DISTRICT_ALL_ERROR: "GET_DISTRICT_ALL_ERROR",
};

export const ProductNamesGetTypes = {
  PRODUCT_NAMES_GET: "PRODUCT_NAMES_GET",
  PRODUCT_NAMES_GET_SUCCESS: "PRODUCT_NAMES_GET_SUCCESS",
  PRODUCT_NAMES_GET_ERROR_SHOW: "PRODUCT_NAMES_GET_ERROR_SHOW",
  PRODUCT_NAMES_GET_ERROR_HIDE: "PRODUCT_NAMES_GET_ERROR_HIDE",
  PRODUCT_NAMES_GET_STATE_CLEAR: "PRODUCT_NAMES_GET_STATE_CLEAR",
};

export const MerchantNamesGetTypes = {
  MERCHANT_NAMES_GET: "MERCHANT_NAMES_GET",
  MERCHANT_NAMES_GET_SUCCESS: "MERCHANT_NAMES_GET_SUCCESS",
  MERCHANT_NAMES_GET_ERROR_SHOW: "MERCHANT_NAMES_GET_ERROR_SHOW",
  MERCHANT_NAMES_GET_ERROR_HIDE: "MERCHANT_NAMES_GET_ERROR_HIDE",
  MERCHANT_NAMES_GET_STATE_CLEAR: "MERCHANT_NAMES_GET_STATE_CLEAR",
};

export const CategoryNamesGetTypes = {
  CATEGORY_NAMES_GET: "CATEGORY_NAMES_GET",
  CATEGORY_NAMES_GET_SUCCESS: "CATEGORY_NAMES_GET_SUCCESS",
  CATEGORY_NAMES_GET_ERROR_SHOW: "CATEGORY_NAMES_GET_ERROR_SHOW",
  CATEGORY_NAMES_GET_ERROR_HIDE: "CATEGORY_NAMES_GET_ERROR_HIDE",
  CATEGORY_NAMES_GET_STATE_CLEAR: "CATEGORY_NAMES_GET_STATE_CLEAR",
};

export const SpecificCustomers = {
  GET_CUSTOMER_LIST_S: "GET_CUSTOMER_LIST_S",
  GET_CUSTOMER_LIST_SUCCESS_S: "GET_CUSTOMER_LIST_SUCCESS_S",
  GET_CUSTOMER_LIST_ERROR_S: "GET_CUSTOMER_LIST_ERROR_S",
};

export const GetMerchantCategoriesTypes = {
  GET_MERCHANT_CATEGORIES_LIST:             "GET_MERCHANT_CATEGORIES_LIST",
  GET_MERCHANT_CATEGORIES_LIST_SUCCESS:     "GET_MERCHANT_CATEGORIES_LIST_SUCCESS",
  GET_MERCHANT_CATEGORIES_LIST_ERROR_SHOW:  "GET_MERCHANT_CATEGORIES_LIST_ERROR_SHOW",
  GET_MERCHANT_CATEGORIES_LIST_ERROR_HIDE:  "GET_MERCHANT_CATEGORIES_LIST_ERROR_HIDE",
  GET_MERCHANT_CATEGORIES_LIST_STATE_CLEAR: "GET_MERCHANT_CATEGORIES_LIST_STATE_CLEAR",
};

export const PromoElasticProductSearch = {
  PROMO_PRODUCT_SEARCH_ELASTIC:             "PROMO_PRODUCT_SEARCH_ELASTIC",
  PROMO_PRODUCT_SEARCH_ELASTIC_SUCCESS:     "PROMO_PRODUCT_SEARCH_ELASTIC_SUCCESS",
  PROMO_PRODUCT_SEARCH_ELASTIC_ERROR_SHOW:  "PROMO_PRODUCT_SEARCH_ELASTIC_ERROR_SHOW",
  PROMO_PRODUCT_SEARCH_ELASTIC_ERROR_HIDE:  "PROMO_PRODUCT_SEARCH_ELASTIC_ERROR_HIDE",
};
